### ISSUE TITLE
Where's the button?

### ISSUE THREAD

**Issue by RedDeadRandy** [felixire/Reddit-Downloader#1]
Is this supposed to work with and/or without the redesign? Does it conflict with RES? What about browsing via old.reddit.com (forces legacy design without changing user prefs).

**Comment by felixire** [comment]
Currently this only works on the default (www.reddit.com) page. Didn't even know that the others existed. But I am working on adding support for both old and new Reddit. 
Never used RES before and I can't currently test if there are any conflicts, but as far as I can tell there shouldn't be.
